### ISSUE TITLE
Adding faces to dog show and remote control mode.

### ISSUE THREAD

**Issue by JKWiniger** [Keyvanhardani/xgo2-robot-eye-and-mouth#1]
Can this be swapped in to replace the faces used during the dog show? Most of that file is handling the face with only a few lines for the actual movements and the song that gets played.

I wanted to find a way to have the faces from the dog show start playing when we were in remote control mode instead of just showing the network connected screen. I was thinking if it started after maybe 10 second and could press a key so break out of it like with other things.

**Comment by Keyvanhardani** [comment]
Absolutely, you can swap in different faces for the dog show. It'll require some adjustments and graphic work. This approach offers greater possibilities for customizing the dog's expressions.

**Comment by JKWiniger** [comment]
I tried running, "pthyon3 eye-mouth-controller.py" I received this error:

pi@raspberrypi:~/RaspberryPi-CM4-main/xgo2-robot-eyes-and-mouth $ python3 eye_mouth_controller.py 
/home/pi/RaspberryPi-CM4-main/xgo2-robot-eyes-and-mouth/eye_mouth_controller.py:25: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  open_eyes_scaled = open_eyes.resize((int(open_eyes.width * EYE_SCALE_FACTOR), int(open_eyes.height * EYE_SCALE_FACTOR)), Image.ANTIALIAS)
/home/pi/RaspberryPi-CM4-main/xgo2-robot-eyes-and-mouth/eye_mouth_controller.py:26: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  closed_eyes_scaled = closed_eyes.resize((int(closed_eyes.width * EYE_SCALE_FACTOR), int(closed_eyes.height * EYE_SCALE_FACTOR)), Image.ANTIALIAS)
/home/pi/RaspberryPi-CM4-main/xgo2-robot-eyes-and-mouth/eye_mouth_controller.py:40: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use LANCZOS or Resampling.LANCZOS instead.
  scaled_image = image.resize((int(image.width * MOUTH_SCALE_FACTOR), int(image.height * MOUTH_SCALE_FACTOR)), Image.ANTIALIAS)

And trying to run, "python3  universal-eyes-mouth.py" I received this error:

/home/pi/RaspberryPi-CM4-main/xgo2-robot-eyes-and-mouth/universal-eyes-mouth.py:52: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  fig, ax = plt.subplots()
/home/pi/RaspberryPi-CM4-main/xgo2-robot-eyes-and-mouth/universal-eyes-mouth.py:79: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.pause(0.1)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/RaspberryPi-CM4-main/xgo2-robot-eyes-and-mouth/universal-eyes-mouth.py", line 79, in show_mouth_animation
    plt.pause(0.1)
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/pyplot.py", line 582, in pause
    canvas.start_event_loop(interval)
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/backends/backend_qt.py", line 421, in start_event_loop
    with _maybe_allow_interrupt(event_loop):
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/backends/qt_compat.py", line 209, in _maybe_allow_interrupt
    old_wakeup_fd = signal.set_wakeup_fd(wsock.fileno())
ValueError: set_wakeup_fd only works in main thread of the main interpreter

(process:1816): GLib-CRITICAL **: 08:19:13.899: g_main_context_pop_thread_default: assertion 'stack != NULL' failed
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by JKWiniger** [comment]
In eye_mouth_controller.py I replaced ANTIALIAS with LANCZOS in 3 spots and the error are gone, but it didn't help universal-eyes-mouth.py

**Comment by Keyvanhardani** [comment]
Fix coming in next days.
